### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by Bence98007** [corux/seafile-cli-windows#3]
Hi there!

I just wanted to ask if this Seafile CLI still works? And how can I download it?

Thanks! :)

**Comment by corux** [comment]
Hi @Bence98007 !
this application still works, also with the current Seafile server version 6.3.4.
Here are the github releases: https://github.com/corux/seafile-cli-windows/releases
Download the file `seafile-cli.exe` from there.

If you have any other questions, feel free to re-open the issue!
