### ISSUE TITLE
Any plan to support download and other featrues?

### ISSUE THREAD

**Issue by betterRunner** [corux/seafile-cli-windows#4]
Hi there, thanks for the effort!

I want to ask for some other features beside uploading such as downloading and so on.
Just much the same as the ones in seafile-cli: https://help.seafile.com/en/syncing_client/linux-cli.html

**Comment by corux** [comment]
Hi @betterRunner,

currently I don't plan to add downloading and other sync features. If you need to sync seafile libraries, you'll better use the official clients.

I had originally created this tool to allow uploads of single files, without the need to sync the whole library.

If you need to download single files, feel free to open a pull request. I'd be happy for your contribution!

**Comment by betterRunner** [comment]
Hi @corux ,

Thanks for the replying! Understood, your upload feature is great by the way. I would consider if I have enough time to make the pull request. Thanks again!
